[build-system]
requires = [
    "setuptools>=45",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = 'py37'

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py37']
include = '\.pyi?$'
